from typing import TypedDict, Annotated, List, Dict, Any, Optional
from pydantic import BaseModel, Field
import operator

# Output Schema for the DECISOR node
# This guarantees the LLM will output a strictly formatted JSON.
class TradeDecision(BaseModel):
    ticker: str = Field(description="The ticker symbol of the stock")
    action: str = Field(description="The action to take: 'BUY', 'SELL', or 'HOLD'")
    quantity: int = Field(description="The number of shares to trade. Set to 0 if HOLD.")
    news_summary: str = Field(description="Brief summary of the news considered for this decision")
    current_price: float = Field(description="The current market price of the asset")
    rationale: str = Field(description="Explicit and detailed reasoning for the decision (Why buy/sell/hold?)")

# Graph State definition
# This represents the data moving through INIT_PORTFOLIO -> DECISOR -> CHECKER -> EXECUTER -> SUMMARIZER
class AgentState(TypedDict):
    # Portfolio data fetched from Alpaca
    portfolio: Dict[str, Any]
    
    # Tickers we are currently analyzing
    target_tickers: List[str]
    
    # The decision generated by the DECISOR
    proposed_decision: Optional[TradeDecision]
    
    # Validation flag set by the CHECKER (True if ACCEPT, False if REJECT)
    is_decision_valid: bool
    
    # SUMMARIZER memory: keeping track of the last N actions
    last_n_actions: List[Dict[str, Any]]
    
    # Journal logs: using Annotated with operator.add to automatically append items to the list
    journal: Annotated[List[Dict[str, Any]], operator.add]
    
    # Error tracking (useful for fallback logic and the Best Recovery challenge)
    error_message: Optional[str]
